### ISSUE TITLE
Periodical Screen Timeout Tile bug

### ISSUE THREAD

**Issue by wiskiw** [mustafa01ali/Dev-Tiles#14]
Sometimes Screen Timeout tile doesn't react on my taps. That can happen on first tap or on another. I'm not sure what is the cause. Look at the [screen record](https://youtu.be/Gv3glFhuhsc) to see what I mean.

**Comment by mustafa01ali** [comment]
That tile is not a part of this app. The only tile related to screen timeout looks like this - 

<img width="84" alt="screen shot 2017-03-22 at 3 06 11 pm" src="https://cloud.githubusercontent.com/assets/767705/24191248/395b4356-0f11-11e7-903b-a5b1c90a4520.png">
