### ISSUE TITLE
Dev-Tiles on F-Droid 

### ISSUE THREAD

**Issue by AlvaroBrey** [mustafa01ali/Dev-Tiles#26]
Hello,

Thanks for this app. It's really useful for development.

I would like to add Dev-Tiles to F-Droid to provide a way to install them without Google services. F-Droid requires me to contact the author first and get his consent.

Do you give this consent?

Cheers!

**Comment by mustafa01ali** [comment]
Hi, someone else has already made this app available on F-Droid - https://apt.izzysoft.de/fdroid/index/apk/xyz.mustafaali.devqstiles
